baseURL = 'https://blog.darrkenn.com'
title = "darrkenn"
languageCode = 'en-us'
defaultContentLanguage = "en-gb"
theme = "hugo-blog-awesome"
ignoreErrors = ["additional-script-loading-error"]

[markup]
[markup.highlight]
noClasses = true
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[languages.en-gb]
[[languages.en-gb.menu.main]]
pageRef = "/"
name = "Home"
url = "/"
weight = 10
[[languages.en-gb.menu.main]]
pageRef = "/posts"
name = "Posts"
url = "/posts/"
weight = 20
[[languages.en-gb.menu.main]]
pageRef = "/about"
name = "About"
url = "https://darrkenn.com"
weight = 20

[languages.en-gb.params]
sitename = "darrkenn | blog"
defaultColor = "dark"
description = "Eh, I'll post a blog tomorrow"
mainSections = ['posts']
toc = false
tocOpen = false
goToTop = true

[languages.en-gb.params.author]
intro = "darrkenn"
name = "darrkenn"
description = "Eh, I'll post a blog tomorrow"


[[params.socialIcons]]
name = "github"
url = "https://github.com/darrkenn"
